In [1]:
import numpy as np
energy_consumption=np.array([1200,3400,2900,1800,2500])
print("\nEnergy Consumption:")
print(energy_consumption)


Energy Consumption:
[1200 3400 2900 1800 2500]


In [17]:
mylist=[[1,2,3],[4,5,6,],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.random.randn(4)

array([-0.20566436, -0.42067397,  0.42485438, -1.55109076])

In [7]:
np.random.rand(4,4)

array([[0.37468224, 0.03025187, 0.58367678, 0.01957802],
       [0.08601401, 0.75152824, 0.14765488, 0.78099597],
       [0.78294946, 0.40984153, 0.0531497 , 0.12636542],
       [0.06848295, 0.73423452, 0.26171315, 0.97797317]])

In [29]:
#.dim
x=np.random.rand(5)
np.max(x)

0.9222232832026948

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.ones(2)

array([1., 1.])

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
total_consumption=np.sum(energy_consumption)
print(f"total energy consumption: {total_consumption}")

total energy consumption: 11800


In [51]:
mean_consumption=np.mean(energy_consumption)
print(f"mean energy consumption {mean_consumption:.2f}")

mean energy consumption 2360.00


In [59]:
std_consumption=np.std(energy_consumption)
print(f"standard deviation energy consumption {std_consumption:.2f}")

standard deviation energy consumption 781.28


In [61]:
reshaped_array=energy_consumption.reshape((5,1))
print("reshaped energy array(5x1): ")
print(reshaped_array)

reshaped energy array(5x1): 
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]
